Output ./.github/assets/demo.gif
Require spilltea

Set Shell "zsh"
Set FontSize 32
Set Width 1600
Set Height 1900

Type "spilltea"
Sleep 800ms
Enter
Sleep 3s

Down@800ms 2
Up@800ms 1
Enter@800ms 1

Wait+Screen     /hadi.icu/
Sleep 3s

Ctrl+Y
Sleep 3s

Down@1.9 4
Escape@1.3 1

Ctrl+R
Sleep 3s
Type "e"
Sleep 1s
Escape
Sleep 1s
Type "s"
Sleep 6s

Type "1"
Sleep 2s
Type "f"
Sleep 2s
Type "2"
Sleep 2s
